config/routes.rb
Rails.application.routes.draw do

  namespace 'api' do
    get '/mobile_app', :to => 'mobile_app#index', :as => 'mobile_app'

    post '/reports', :to => 'reports#create', :as => 'reports'
    get '/reports/structure', :to => 'reports#structure', :as => 'reports_structure'
    post '/reports/:id/photo', :to => 'reports#photo', :as => 'reports_photo'

    get '/shops', :to => 'shops#index', :as => 'shops'

    get '/settings/versions', :to => 'settings#versions', :as => 'settings_versions'

    post '/users/sign_in', :to => 'users#sign_in', :as => 'sign_in'
    post '/users/geolocation', :to => 'users#geolocation', :as => 'user_geolocation'
  end

  scope '(:locale)' do
    get '/charts/reports_score', :to => 'charts#reports_score', :as => 'reports_score_chart'
    get '/charts/reports_count', :to => 'charts#reports_count', :as => 'reports_count_chart'

    resources :cities do
      member do
        get 'restore'
        patch 'restore_info'
      end
    end

    resources :dealers do
      member do
        get 'restore'
      end
    end

    resources :employees do
      member do
        get 'restore'
      end
    end

    resources :employee_workpositions do
      member do
        get 'restore'
      end
    end

    resources :items

    resources :regions do
      member do
        get 'restore'
      end
    end

    resources :reports, :only => [:index, :show]

    resources :report_structure_categories do
      member do
        get 'increase_priority'
        get 'decrease_priority'
      end
    end

    resources :report_structure_elements do
      member do
        get 'increase_priority'
        get 'decrease_priority'
      end
    end

    get '/report_structure', :to => 'report_structure_categories#index', :as => 'report_structure'

    resources :settings, :only => [:index, :edit, :update]

    resources :shops do
      collection do
        get 'map_info'
      end

      member do
        get 'info'
        get 'restore'
        patch 'restore_info'
      end

      resources :employees do
        member do
          get 'restore'
        end
      end

      resources :shop_items, :only => [:index, :new, :create, :destroy]
    end

    resources :shop_items

    resources :shop_photos

    resources :shop_types do
      member do
        get 'restore'
      end
    end

    devise_for :users, controllers: { sessions: "users/sessions" }
    resources :users do
      member do
        get 'restore'
      end
    end

    resources :user_locations, :only => [:index] do
      collection do
        get 'map'
      end
    end

    resources :user_devices, :only => [:index, :destroy]
  end

  root 'dashboard#index'
  get '/:locale' => 'dashboard#index'
  match '/settings/review_associated_shops' => 'settings#review_associated_shops', via: [:get, :post]

end

app/controllers/shop_types_controller.rb
class ShopTypesController < ApplicationController
  before_action :load_shop_type, only: [:show, :edit, :update, :destroy]
  
  # GET /shop_types
  def index
    @shop_types = policy_scope(ShopType)
    @shop_types = @shop_types.filter(filtering_params).order(:name)
  end

  # GET /shop_types/1
  def show
  end

  # GET /shop_types/new
  def new
    @shop_type = ShopType.new
    session[:return_to] = request.referer unless request.referer == request.url
  end

  # GET /shop_types/1/edit
  def edit
    session[:return_to] = request.referer unless request.referer == request.url
  end

  # POST /shop_types
  def create
    @shop_type = ShopType.new(shop_type_params)

    if @shop_type.save
      flash[:success] = t('controllers.shop_types.created', name: @shop_type.name)
      redirect_to session.delete(:return_to) || shop_types_url
    else
      render :new
    end
  end

  # PATCH/PUT /shop_types/1
  def update
    if @shop_type.update(shop_type_params)
      flash[:success] = t('controllers.shop_types.updated', name: @shop_type.name)
      redirect_to session.delete(:return_to) || shop_types_url
    else
      render :edit
    end
  end

  # DELETE /shop_types/1
  def destroy
    @shop_type.soft_delete
    flash[:success] = t('controllers.shop_types.destroyed', name: @shop_type.name)
    redirect_to request.referer
  end
  
  # GET /shop_types/1/restore
  def restore
    @shop_type = ShopType.deleted.find(params[:id])
    @shop_type.restore

    flash[:success] = t('controllers.shop_types.restored', name: @shop_type.name)
    redirect_to request.referer
  end

  private

  def load_shop_type
    @shop_type = ShopType.find(params[:id])
  end

  def shop_type_params
    params.require(:shop_type).permit(:name, :abbreviation)
  end

  def filtering_params
    params.fetch(:filter, {}).permit(:name, :is_deleted)
  end
end

app/views/shop_types/_filter.html.haml
- filtering_params = params[:filter] || {}

.row
  .col-lg-offset-1.col-lg-10
    .panel.panel-default
      .panel-body

        %form{:role => 'form'}
          .row
            .form-group.col-sm-4
              %label{:for => 'name'}= t('activerecord.attributes.shop_type.name')
              %input#name.form-control.input-sm{:type => 'text', :name => 'filter[name]', :value => filtering_params[:name], :autocomplete => :off}

            .form-group.col-sm-2
              %label &nbsp;
              .checkbox{:style => 'margin: 0px;'}
                %label
                  %input{:type => 'checkbox', :name => 'filter[is_deleted]', :checked => (not filtering_params[:is_deleted].blank?)}
                    %strong= t('activerecord.attributes.shop_type.is_deleted')

            .form-group.col-sm-2
              %label.text-block &nbsp;
              %input.btn.btn-block.btn-sm.btn-default{:type => 'submit', :value => t('views.common.filter')}

app/views/shop_types/_form.html.haml
= simple_form_for @shop_type, :html => {:class => 'form-horizontal', :role => 'form'} do |f|

  = f.input :name
  = f.input :abbreviation

  .btn-toolbar.text-center
    = f.button :submit, t('views.common.save')
    %a.btn.btn-default{:href => session[:return_to] || shop_types_path}= t('views.common.cancel')

app/views/shop_types/edit.html.haml
%h2.text-center= t('views.shop_types.edit', :name => @shop_type.name_was)
%br

= render 'form'

app/views/shop_types/index.html.haml
%h2.text-center= t('views.shop_types.list')
%br

= render 'filter'

.row
  .col-lg-offset-1.col-lg-10
    .panel.panel-default
      .table-responsive
        %table.table.table-condensed.table-striped.table-vcentered
          %thead
            %tr
              %th= t('activerecord.attributes.shop_type.name')
              %th= t('activerecord.attributes.shop_type.abbreviation')
              %th.text-right
                - if policy(ShopType).create?
                  %a.btn.btn-default.btn-xs{:href => new_shop_type_path, :title => t('views.common.add'), :data => {:toggle => "tooltip"}}
                    %span.glyphicon.glyphicon-plus
          %tbody
            -if @shop_types.any?
              - @shop_types.each do |shop_type|
                %tr
                  %td= link_to shop_type.name, shops_url(:filter => {:type => shop_type.id})
                  %td= shop_type.abbreviation
                  %td.text-right
                    - if policy(shop_type).restore?
                      %a.btn.btn-default.btn-xs{:href => restore_shop_type_path(shop_type), :title => t('views.common.restore'), :data => {:toggle => "tooltip"}}
                        %span.glyphicon.glyphicon-ok
                    - if policy(shop_type).destroy?
                      %a.btn.btn-default.btn-xs{:href => shop_type_path(shop_type), :title => t('views.common.delete'), :data => {:toggle => "tooltip", :method => 'delete', :confirm => t('views.common.confirm')}}
                        %span.glyphicon.glyphicon-remove
                    - if policy(shop_type).update?
                      %a.btn.btn-default.btn-xs{:href => edit_shop_type_path(shop_type), :title => t('views.common.edit'), :data => {:toggle => "tooltip"}}
                        %span.glyphicon.glyphicon-edit
            -else
              %tr
                %td{:colspan => 3}
                  %h4.text-center= t('views.common.empty')

app/views/shop_types/new.html.haml
%h2.text-center= t('views.shop_types.new')
%br

= render 'form'