config/routes.rb
Rails.application.routes.draw do

  namespace 'api' do
    get '/mobile_app', :to => 'mobile_app#index', :as => 'mobile_app'

    post '/reports', :to => 'reports#create', :as => 'reports'
    get '/reports/structure', :to => 'reports#structure', :as => 'reports_structure'
    post '/reports/:id/photo', :to => 'reports#photo', :as => 'reports_photo'

    get '/shops', :to => 'shops#index', :as => 'shops'

    get '/settings/versions', :to => 'settings#versions', :as => 'settings_versions'

    post '/users/sign_in', :to => 'users#sign_in', :as => 'sign_in'
    post '/users/geolocation', :to => 'users#geolocation', :as => 'user_geolocation'
  end

  scope '(:locale)' do
    get '/charts/reports_score', :to => 'charts#reports_score', :as => 'reports_score_chart'
    get '/charts/reports_count', :to => 'charts#reports_count', :as => 'reports_count_chart'

    resources :cities do
      member do
        get 'restore'
        patch 'restore_info'
      end
    end

    resources :dealers do
      member do
        get 'restore'
      end
    end

    resources :employees do
      member do
        get 'restore'
      end
    end

    resources :employee_workpositions do
      member do
        get 'restore'
      end
    end

    resources :items

    resources :regions do
      member do
        get 'restore'
      end
    end

    resources :reports, :only => [:index, :show]

    resources :report_structure_categories do
      member do
        get 'increase_priority'
        get 'decrease_priority'
      end
    end

    resources :report_structure_elements do
      member do
        get 'increase_priority'
        get 'decrease_priority'
      end
    end

    get '/report_structure', :to => 'report_structure_categories#index', :as => 'report_structure'

    resources :settings, :only => [:index, :edit, :update]

    resources :shops do
      collection do
        get 'map_info'
      end

      member do
        get 'info'
        get 'restore'
        patch 'restore_info'
      end

      resources :employees do
        member do
          get 'restore'
        end
      end

      resources :shop_items, :only => [:index, :new, :create, :destroy]
    end

    resources :shop_items

    resources :shop_photos

    resources :shop_types do
      member do
        get 'restore'
      end
    end

    devise_for :users, controllers: { sessions: "users/sessions" }
    resources :users do
      member do
        get 'restore'
      end
    end

    resources :user_locations, :only => [:index] do
      collection do
        get 'map'
      end
    end

    resources :user_devices, :only => [:index, :destroy]
  end

  root 'dashboard#index'
  get '/:locale' => 'dashboard#index'
  match '/settings/review_associated_shops' => 'settings#review_associated_shops', via: [:get, :post]

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include Modules::SoftDelete
  include Modules::Filterable
  include Modules::Sortable

  belongs_to :type,   :class_name => 'ShopType', :foreign_key => 'shop_type_id'
  belongs_to :city,   touch: true
  belongs_to :dealer, touch: true
  belongs_to :user,   -> { where(:role => UserRole.reviewer) }

  has_one :region, :through => :city

  has_many :photos,     :class_name => 'ShopPhoto'
  has_many :shop_items
  has_many :employees
  has_many :reports

  validates :type,  :presence => true
  validates :city,  :presence => true
  validates :dealer,  :presence => true
  validates :user,  :presence => true
  validates :address,  :presence => true

  scope :with_type, -> (type) { where(:type => type) }
  scope :with_city, -> (city) { where(:city => city) }
  scope :with_dealer, -> (dealer) { where(:dealer => dealer) }
  scope :with_user, -> (user) { where(:user => user) }
  scope :with_address, -> (address) { where("address ilike ?", "%#{address}%") }
  scope :with_is_deleted, -> (is_deleted) { deleted unless is_deleted.blank? }
  scope :with_region, -> (region) { joins(:city).where(:cities => {:region_id => region}) }

  scope :by_type, -> (dir) { joins(:type).order("shop_types.name #{dir}") }
  scope :by_dealer, -> (dir) { joins(:dealer).order("dealers.name #{dir}") }
  scope :by_user, -> (dir) { includes(:user).order("users.name #{dir} nulls last") }
  scope :by_address, -> (dir) { joins(:city).order("cities.name #{dir}, address #{dir}") }
  scope :by_score, -> (dir) { order("score #{dir} nulls last")}

  before_soft_delete :delete_shop_items, :delete_employees

  def name
    City.unscoped do
      [city.name, address].join(', ')
    end
  end

  def name_was
    City.unscoped do
      city_was = Shop.with_deleted.find(self.id).city
      [city_was.name, address_was].join(', ')
    end
  end

  def last_report
    reports.order('created_at desc').first
  end

  def self.not_reviewed(date)
    last_reports = Report.select("distinct on(shop_id) shop_id, created_at").order("shop_id, created_at desc").to_sql
    return Shop.joins("left outer join (#{last_reports}) as reports on reports.shop_id = shops.id").where("reports.created_at < ? or reports.created_at is null", date)
  end

  private

  def delete_shop_items
    shop_items.each do |item|
      item.destroy
    end
  end

  def delete_employees
    employees.each do |employee|
      employee.soft_delete
    end
  end
end

app/models/shop_type.rb
class ShopType < ActiveRecord::Base
  include Modules::SoftDelete
  include Modules::Filterable

  validates :name, :presence => true, :uniqueness => true
  validates :abbreviation, :presence => true, :uniqueness => true

  has_many :shops

  scope :with_name, -> (name) { where("name ilike ?", "%#{name}%") }
  scope :with_is_deleted, -> (is_deleted) { deleted unless is_deleted.blank? }
end

app/controllers/api/shops_controller.rb
class Api::ShopsController < Api::ApiController

  # GET /shops
  def index
    begin
      if Setting.find_by_name('review_associated_shops').value == 'yes'
        @shops_by_dealer = Dealer.all.map do |d|
            [d, d.shops.where(:user => current_user).group_by { |s| s.city }]
          end
      else
        @shops_by_dealer = Dealer.all.map{ |d| [d, d.shops.group_by{|s| s.city}] }
      end

      @shops_by_dealer = Hash[@shops_by_dealer]
      @shops_by_dealer.each do |dealer, cities|
        cities.delete_if { |city, shops| shops.blank? }
      end
      @shops_by_dealer.delete_if { |dealer, cities| cities.blank? }
    rescue Exception => ex
      @msg = ex.message
      render 'api/common/error'
    end
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :load_shop, only: [:show, :edit, :update, :destroy, :info]
  before_action :load_shops, only: [:index, :map_info]
  helper_method :sorting_params

  # GET /shops
  def index
    @shops = @shops.filter(filtering_params).sort(sorting_params).page(params[:page])
  end

  # GET /shops/1
  def show
    @reports = @shop.reports.by_created_at('DESC').page(params[:page]).per(10)
  end

  # GET /shops/new
  def new
    @shop = Shop.new
    session[:return_to] = request.referer unless request.referer == request.url
  end

  # GET /shops/1/edit
  def edit
    session[:return_to] = request.referer unless request.referer == request.url
  end

  # POST /shops
  def create
    @shop = Shop.new(shop_params)

    if @shop.save
      flash[:success] = t('controllers.shops.created', name: @shop.name)
      redirect_to session.delete(:return_to) || shops_url
    else
      render :new
    end
  end

  # PATCH/PUT /shops/1
  def update
    if @shop.update(shop_params)
      flash[:success] = t('controllers.shops.updated', name: @shop.name)
      redirect_to session.delete(:return_to) || shops_url
    else
      render :edit
    end
  end

  # DELETE /shops/1
  def destroy
    @shop.soft_delete

    flash[:success] = t('controllers.shops.destroyed', name: @shop.name)
    redirect_to request.referer
  end

  # GET /shops/1/restore
  def restore
    session[:return_to] = request.referer  unless request.referer == request.url
    @shop = Shop.deleted.find(params[:id])
  end

  # GET /shops/1/restore_info
  def restore_info
    @shop = Shop.deleted.find(params[:id])
    
    if @shop.update(shop_params)
      @shop.restore
      flash[:success] = t('controllers.shops.restored', name: @shop.name)
      redirect_to session.delete(:return_to) || shops_url
    else
      render :restore
    end
  end

  # GET /shops/1/info
  def info
    if request.xhr?
      render :partial => 'info', :locals => { :shop => @shop }
    end
  end

  # GET /shops/map_info
  def map_info
    @shops = @shops.filter(filtering_params).all
      .map{ |shop| {:info => info_shop_path(shop), :latitude => shop.latitude, :longitude => shop.longitude} }

    render :json => @shops
  end

  private

  def load_shop
    @shop = Shop.find(params[:id])
  end

  def load_shops
    @shops = policy_scope(Shop)
  end

  def shop_params
    params.require(:shop).permit(:shop_type_id, :city_id, :address, :latitude, :longitude,
      :dealer_id, :square_footage, :user_id, :is_deleted)
  end

  def filtering_params
    params.fetch(:filter, {}).permit(:type, :city, :region, :address, :dealer, :user, :is_deleted)
  end

  def sorting_params
    params.fetch(:sort, {:col => "type", :dir => "asc"}).permit(:col, :dir)
  end
end

app/views/shops/_filter.html.haml
- filtering_params = params[:filter] || {}

.row
  .col-lg-offset-1.col-lg-10
    .panel.panel-default
      .panel-body

        %form{:role => 'form'}
          .row
            .form-group.col-sm-2
              %label{:for => 'type'}= t('activerecord.attributes.shop.type')
              %select#type.form-control.input-sm{:type => 'text', :name => 'filter[type]'}
                %option{:value => ''}= t('views.common.all')
                - ShopType.all.each do |type|
                  %option{:value => type.id, :selected => filtering_params[:type].to_i == type.id}= type.name

            .form-group.col-sm-2
              %label{:for => 'city'}= t('activerecord.attributes.shop.city')
              %select#city.form-control.input-sm{:type => 'text', :name => 'filter[city]'}
                %option{:value => ''}= t('views.common.all')
                - City.all.each do |city|
                  %option{:value => city.id, :selected => filtering_params[:city].to_i == city.id}= city.name

            .form-group.col-sm-2
              %label{:for => 'address'}= t('activerecord.attributes.shop.address')
              %input#address.form-control.input-sm{:type => 'text', :name => 'filter[address]', :value => filtering_params[:address], :autocomplete => :off}

            - if policy(Shop).filter_dealer?
              .form-group.col-sm-2
                %label{:for => 'dealer'}= t('activerecord.attributes.shop.dealer')
                %select#dealer.form-control.input-sm{:type => 'text', :name => 'filter[dealer]'}
                  %option{:value => ''}= t('views.common.all')
                  - Dealer.all.each do |dealer|
                    %option{:value => dealer.id, :selected => filtering_params[:dealer].to_i == dealer.id}= dealer.name

            - if policy(Shop).filter_reviewer?
              .form-group.col-sm-2
                %label{:for => 'user'}= t('activerecord.attributes.shop.user')
                %select#user.form-control.input-sm{:type => 'text', :name => 'filter[user]'}
                  %option{:value => ''}= t('views.common.all')
                  - UserRole.reviewer.users.all.each do |user|
                    %option{:value => user.id, :selected => filtering_params[:user].to_i == user.id}= user.full_name

            .form-group.col-sm-2
              %label &nbsp;
              .checkbox{:style => 'margin: 0px;'}
                %label
                  %input{:type => 'checkbox', :name => 'filter[is_deleted]', :checked => (not filtering_params[:is_deleted].blank?)}
                    %strong= t('activerecord.attributes.user.is_deleted')
          .row
            .col-sm-offset-5.col-sm-2
              %input.btn-block.btn.btn-default.btn-sm{:type => 'submit', :value => t('views.common.filter')}

app/views/shops/_form.html.haml
- if @shop.persisted?
  = stylesheet_link_tag 'jquery.fileupload-ui'
  = javascript_include_tag 'jquery.fileupload'
  = javascript_include_tag 'photo_uploader'

  = simple_form_for @shop.photos.build, :html => {:id => 'photoupload'} do |f|
    .row
      .col-sm-2.col-xs-4
        %span.btn.btn-xs.btn-primary.fileinput-button
          %i.glyphicon.glyphicon-plus
          %span= t('views.shops.add_photo')
          = f.input_field :photo, :as => :file, :accept => "image/jpeg, image/png, image/gif, image/jpg"

      .col-sm-10.col-xs-8
        .progress.progress-xs
          .progress-bar{:role => 'progressbar', :style => "width: 0%;"} 0%

    = f.input_field :shop_id, :as => :hidden

    = render 'shop_photos/galery', :shop => @shop

.row
  .col-sm-6
    .panel.panel-default
      .panel-body
        #map_canvas.map-container

  .col-sm-6
    = simple_form_for @shop, :url => (action if defined?(action)), :html => {:class => 'form-horizontal', :role => 'form'} do |f|

      = f.association :type
      = f.association :city
      = f.input :address
      = f.input :latitude
      = f.input :longitude
      = f.association :dealer
      = f.input :square_footage
      = f.association :user, :collection => UserRole.reviewer.users.map{ |u| [u.full_name, u.id] }

      .btn-toolbar.text-center
        = f.button :submit, t('views.common.save')
        %a.btn.btn-default{:href => session[:return_to] || shops_path}= t('views.common.cancel')

app/views/shops/_info.html.haml
%table#general-info.table.table-condensed.table-striped
  %tbody
    %tr
      %td= t('activerecord.attributes.shop.region')
      %td= can_link_to shop.region.name, shop.region
    %tr
      %td= t('activerecord.attributes.shop.city')
      %td= can_link_to shop.city.name, shop.city
    %tr
      %td= t('activerecord.attributes.shop.address')
      %td= can_link_to shop.address, shop
    %tr
      %td= t('activerecord.attributes.shop.type')
      %td= shop.type.name
    %tr
      %td= t('activerecord.attributes.shop.square_footage')
      %td= shop.square_footage || '-'
    %tr
      %td= t('activerecord.attributes.shop.dealer')
      %td= can_link_to shop.dealer.name, shop.dealer
    %tr
      %td= t('activerecord.attributes.shop.user')
      %td= shop.user ? can_link_to(shop.user.full_name, shop.user) : '-'
    %tr
      %td= t('activerecord.attributes.shop.score')
      %td= shop.score ? can_link_to(shop.score, shop.last_report) : '-'

app/views/shops/_list.html.haml
.table-responsive{:style => ("max-height:#{max_height}px;" if defined?(max_height))}
  %table.table.table-condensed.table-striped.table-vcentered
    %thead
      %tr
        - if params[:controller] == 'shops'
          %th= sortable(:type, t('activerecord.attributes.shop.type'))
          %th= sortable(:address, t('activerecord.attributes.shop.address'))
          %th= sortable(:dealer, t('activerecord.attributes.shop.dealer'))
          %th= sortable(:user, t('activerecord.attributes.shop.user'))
          %th= sortable(:score, t('activerecord.attributes.shop.score'))

        - else
          %th= t('activerecord.attributes.shop.type')
          %th= t('activerecord.attributes.shop.address')
          - unless params[:controller] == 'dealers'
            %th= t('activerecord.attributes.shop.dealer')
          - unless params[:controller] == 'users'
            %th= t('activerecord.attributes.shop.user')
          %th= t('activerecord.attributes.shop.score')
        %th.text-right
          - if policy(Shop).create?
            %a.btn.btn-default.btn-xs{:href => new_shop_path, :title => t('views.common.add'), :data => {:toggle => 'tooltip'}}
              %span.glyphicon.glyphicon-plus

    %tbody
      - if shops.any?
        - shops.each do |shop|
          %tr
            %td= shop.type.name
            %td= can_link_to shop.name, shop
            - unless params[:controller] == 'dealers'
              - if shop.dealer
                %td= can_link_to shop.dealer.name, shop.dealer
              - else
                %td -
            - unless params[:controller] == 'users'
              - if shop.user
                %td= can_link_to shop.user.full_name, shop.user
              - else
                %td -
            %td= shop.score ? can_link_to(shop.score, shop.last_report) : '-'
            %td.text-right
              - if policy(shop).restore?
                %a.btn.btn-default.btn-xs{:href => restore_shop_path(shop), :title => t('views.common.restore'), :data => {:toggle => 'tooltip'}}
                  %span.glyphicon.glyphicon-ok
              - if policy(shop).update?
                %a.btn.btn-default.btn-xs{:href => edit_shop_path(shop), :title => t('views.common.edit'), :data => {:toggle => 'tooltip'}}
                  %span.glyphicon.glyphicon-edit
              - if policy(shop).destroy?
                %a.btn.btn-default.btn-xs{:href => shop_path(shop), :title => t('views.common.delete'), :data => {:toggle => 'tooltip', :method => 'delete', :confirm => t('views.common.confirm')}}
                  %span.glyphicon.glyphicon-remove

      - else
        %tr
          %td{:colspan => 6}
            %h4.text-center= t('views.common.empty')

app/views/shops/edit.html.haml
= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDMOPJqNEeELfg-Lt9yjIyCez3INjSvKq8&v=3'
=javascript_include_tag "maps/shop_edit"

%h2.text-center= t('views.shops.edit', :name => @shop.name_was)
%br

= render 'form'

app/views/shops/index.html.haml
%h2.text-center= t('views.shops.list')
%br

= render 'filter'

.row
  .col-lg-offset-1.col-lg-10
    .panel.panel-default
      = render 'list', :shops => @shops

    = paginate @shops

app/views/shops/new.html.haml
= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDMOPJqNEeELfg-Lt9yjIyCez3INjSvKq8&v=3'
=javascript_include_tag "maps/shop_edit"

%h2.text-center= t('views.shops.new')
%br

= render 'form'

app/views/shops/restore.html.haml
= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDMOPJqNEeELfg-Lt9yjIyCez3INjSvKq8&v=3'
= javascript_include_tag "maps/shop_edit"

%h2.text-center= t('views.shops.restore', :name => @shop.name_was)
%br

= render 'form', :action => restore_info_shop_path

app/views/shops/show.html.haml
= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDMOPJqNEeELfg-Lt9yjIyCez3INjSvKq8&v=3'
= javascript_include_tag 'http://www.google.com/jsapi'
= javascript_include_tag 'maps/shop_show'
= javascript_include_tag 'chart_helper'

:javascript
  google.load("visualization", "1", {packages:["corechart"]});

= stylesheet_link_tag 'shops'

.well.well-sm
  .row
    .col-md-4.col-sm-12
      .panel.panel-default
        #map_canvas.map-container{:data => {:lat => @shop.latitude, :lng => @shop.longitude}}

    .col-md-4.col-sm-6
      .panel.panel-default
        = render 'info', :shop => @shop
      .btn-toolbar.text-center
        %a.btn.btn-default.btn-sm{:data => {:modal=> 'true', :source => shop_employees_path(@shop)}}= t('views.common.show_employees')
        %a.btn.btn-default.btn-sm{:data => {:modal=> 'true', :source => shop_shop_items_path(@shop)}}= t('views.common.show_items')
      %br
      .btn-toolbar.text-center
        - if policy(@shop).update?
          %a.btn.btn-default.btn-sm{:href => edit_shop_path(@shop)}= t('views.common.edit')
        - if policy(@shop).destroy?
          %a.btn.btn-default.btn-sm{:href => shop_path(@shop), :data => {:method => 'delete', :confirm => t('views.common.confirm')}}= t('views.common.delete')

    .col-md-4.col-sm-6
      .panel.panel-default
        = render 'shop_photos/slideshow', :shop => @shop

- if @reports.any?
  %h3.text-center= t('views.reports.list')
  .row
    .col-sm-6
      = render 'layouts/chart', :container_id => 'score-chart', :source => reports_score_chart_path, :extra_params => {:filter => {:shop => @shop.id}}


    .col-sm-6
      .panel.panel-default
  
        %div.chart-container{:style => 'overflow: auto;'}
          = render 'reports/list', :reports => @reports

      = paginate @reports