config/routes.rb
Rails.application.routes.draw do

  namespace 'api' do
    get '/mobile_app', :to => 'mobile_app#index', :as => 'mobile_app'

    post '/reports', :to => 'reports#create', :as => 'reports'
    get '/reports/structure', :to => 'reports#structure', :as => 'reports_structure'
    post '/reports/:id/photo', :to => 'reports#photo', :as => 'reports_photo'

    get '/shops', :to => 'shops#index', :as => 'shops'

    get '/settings/versions', :to => 'settings#versions', :as => 'settings_versions'

    post '/users/sign_in', :to => 'users#sign_in', :as => 'sign_in'
    post '/users/geolocation', :to => 'users#geolocation', :as => 'user_geolocation'
  end

  scope '(:locale)' do
    get '/charts/reports_score', :to => 'charts#reports_score', :as => 'reports_score_chart'
    get '/charts/reports_count', :to => 'charts#reports_count', :as => 'reports_count_chart'

    resources :cities do
      member do
        get 'restore'
        patch 'restore_info'
      end
    end

    resources :dealers do
      member do
        get 'restore'
      end
    end

    resources :employees do
      member do
        get 'restore'
      end
    end

    resources :employee_workpositions do
      member do
        get 'restore'
      end
    end

    resources :items

    resources :regions do
      member do
        get 'restore'
      end
    end

    resources :reports, :only => [:index, :show]

    resources :report_structure_categories do
      member do
        get 'increase_priority'
        get 'decrease_priority'
      end
    end

    resources :report_structure_elements do
      member do
        get 'increase_priority'
        get 'decrease_priority'
      end
    end

    get '/report_structure', :to => 'report_structure_categories#index', :as => 'report_structure'

    resources :settings, :only => [:index, :edit, :update]

    resources :shops do
      collection do
        get 'map_info'
      end

      member do
        get 'info'
        get 'restore'
        patch 'restore_info'
      end

      resources :employees do
        member do
          get 'restore'
        end
      end

      resources :shop_items, :only => [:index, :new, :create, :destroy]
    end

    resources :shop_items

    resources :shop_photos

    resources :shop_types do
      member do
        get 'restore'
      end
    end

    devise_for :users, controllers: { sessions: "users/sessions" }
    resources :users do
      member do
        get 'restore'
      end
    end

    resources :user_locations, :only => [:index] do
      collection do
        get 'map'
      end
    end

    resources :user_devices, :only => [:index, :destroy]
  end

  root 'dashboard#index'
  get '/:locale' => 'dashboard#index'
  match '/settings/review_associated_shops' => 'settings#review_associated_shops', via: [:get, :post]

end

app/models/report.rb
class Report < ActiveRecord::Base
  include Modules::Filterable
  include Modules::Sortable

  validates :user, :presence => true
  validates :shop, :presence => true
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  validates :score, :presence => true
  validates :created_at, :presence => true

  belongs_to :user, -> { with_deleted }
  belongs_to :shop, -> { with_deleted }

  has_one :city, :through => :shop
  has_one :dealer, :through => :shop

  has_many :elements, :class_name => 'ReportElement'
  has_many :photos, :class_name => 'ReportPhoto'

  accepts_nested_attributes_for :elements

  scope :with_user, -> (user) { where(:user => user) }
  scope :with_shop, -> (shop) { where(:shop => shop) }
  scope :with_score_from, -> (score) { where('score >= ?', score) }
  scope :with_score_to, -> (score) { where('score <= ?', score) }
  scope :with_date_from, -> (date) { where('created_at >= ?', date) }
  scope :with_date_to, -> (date) { where('created_at <= ?', date) }
  scope :with_dealer, -> (dealer) { joins(:shop).where(:shops => {:dealer_id => dealer}) }

  scope :by_created_at, -> (dir) { order("created_at #{dir}") }
  scope :by_score, -> (dir) { order("score #{dir}") }
  scope :by_user, -> (dir) { joins(:user).order("users.name #{dir}, users.surname #{dir}") }
  scope :by_shop, -> (dir) { joins(:city).order("cities.name #{dir}, shops.address #{dir}") }

  MAX_SCORE = 5

  after_create :update_scores

  def structured
    ReportStructureCategory.unscoped do
      elements.group_by(&:category)
    end
  end

  def update_scores
    self.shop.update_attribute(:score, self.score)

    avg_score = dealer.shops.average(:score)
    dealer.update_attribute(:score, avg_score)
  end
end

app/controllers/api/reports_controller.rb
class Api::ReportsController < Api::ApiController

  # GET /reports/structure
  def structure
    begin
      @categories = ReportStructureCategory.order(:priority)
    rescue Exception => ex
      @msg = ex.message
      render 'api/common/error'
    end
  end

  # POST /reports
  def create
    begin
      treated_params = treat_report_params(params[:report])

      @report = Report.new(treated_params)
      unless @report.save
        raise Exception.new(@report.errors.full_messages.join('; '))
      end

    rescue Exception => ex
      @msg = ex.message
      render 'api/common/error'
    end
  end

  # POST /reports/1/photo
  def photo
    begin
      params[:photo].each do |index, photo|
        @report_photo = ReportPhoto.new(
          { :report_id => params[:id], :photo => photo[:file], :comment => photo[:comment] }
        )

        unless @report_photo.save
          raise Exception.new(@report_photo.errors.full_messages.join('; '))
        end
      end

    rescue Exception => ex
      @msg = ex.message
      render 'api/common/error'
    end
  end

  # Helper methods

  def treat_report_params(report_params)
    begin
      score = 0.0
      max_score = 0.0

      geoloc = report_params[:geolocation].split(' ')
      treated_params = {
        latitude: geoloc[0], longitude: geoloc[1],
        shop_id: report_params[:shop_id], user_id: current_user.id,
        created_at: Time.now,
        elements_attributes: []
      }

      report_params[:categories].each do |category|
        category[:elements].each do |element|
          treated_params[:elements_attributes] << {
            name: element[:name], value: element[:value], report_structure_category_id: category[:id],
            report_structure_element_type_id: ReportStructureElementType.find_by_name(element[:type]).id
          }

          element_mark = 0
          element_weight = element[:weight] ? element[:weight].to_i : 0
          case element[:type]
          when 'mark'
            element_mark = element[:value].to_i if element[:value]
          when 'check'
            element_mark = Report::MAX_SCORE if element[:value] == 'yes'
          else
            element_weight = 0
          end
          score += element_mark * element_weight
          max_score += Report::MAX_SCORE * element_weight
        end
      end

      treated_params[:score] = score / max_score * Report::MAX_SCORE

      return treated_params

    rescue Exception => ex
      raise Exception.new("Wrong report format: #{ex.message}")
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :load_report, only: [:show]
  helper_method :sorting_params

  # GET /reports
  def index
    @reports = policy_scope(Report)
    @reports = @reports.filter(filtering_params).sort(sorting_params).page(params[:page])
  end

  # GET /reports/1
  def show
    respond_to do |format|
      format.html
      format.pdf { render :pdf => "#{t('activerecord.models.report')}",
        :template => 'reports/show', :layout => 'layouts/pdf.html.erb', :encoding => 'utf-8;' }
    end
  end

  private

  def load_report
    @report = Report.find(params[:id])
  end

  def filtering_params
    params.fetch(:filter, {}).permit(:user, :shop, :score_from, :score_to, :date_from, :date_to)
  end

  def sorting_params
    params.fetch(:sort, {:col => 'created_at', :dir => 'desc'}).permit(:col, :dir)
  end
end

app/views/reports/_filter.html.haml
= javascript_include_tag 'range_picker'

- filtering_params = params[:filter] || {}

.row
  .col-lg-offset-1.col-lg-10
    .panel.panel-default
      .panel-body

        %form{:role => 'form'}
          .row
            - if policy(Report).filter_reviewer?
              .form-group.col-sm-2
                %label{:for => 'user'}= t('activerecord.attributes.report.user')
                %select#user.form-control.input-sm{:name => 'filter[user]'}
                  %option{:value => ''}= t('views.common.all')
                  - UserRole.reviewer.users.each do |u|
                    %option{:value => u.id, :selected => filtering_params[:user].to_i == u.id}= u.full_name

            - shops = policy_scope(Shop).by_address('asc')
            .form-group.col-sm-3
              %label{:for => 'shop'}= t('activerecord.attributes.report.shop')
              %select#shop.form-control.input-sm{:name => 'filter[shop]'}
                %option{:value => ''}= t('views.common.all')
                - shops.each do |s|
                  %option{:value => s.id, :selected => filtering_params[:shop].to_i == s.id}= s.name

            .form-group.col-sm-4
              %label{:for => 'period'}= t('views.reports.period')
              #period.input-group.input-group-sm{:data => {:rangepicker => 'yes'}}
                %input#date_from.form-control{:type => 'text', :name => 'filter[date_from]', :value => filtering_params[:date_from], :data => {:border => 'from'}}
                %span.input-group-addon -
                %input#date_to.form-control{:type => 'text', :name => 'filter[date_to]', :value => filtering_params[:date_to], :data => {:border => 'from'}}

            - score_params = {:from => (not filtering_params[:score_from].blank?) ? filtering_params[:score_from].to_i : nil, :to => (not filtering_params[:score_to].blank?) ? filtering_params[:score_to].to_i : nil}
            .form-group.col-sm-3
              %label{:for => 'score'}= t('activerecord.attributes.report.score')
              %div
                #score-control.btn-group.btn-group-sm
                  - (0..5).each do |score|
                    - active = (score_params[:from] and score_params[:to] and score.between?(score_params[:from], score_params[:to]))
                    %span.btn.btn-default{:class => "#{'active' if active}", :data => {:value => score}}= score
              
              %input#score-from{:type => 'hidden', :name => 'filter[score_from]', :value => score_params[:from]}
              %input#score-to{:type => 'hidden', :name => 'filter[score_to]', :value => score_params[:to]}

          .btn-toolbar.text-center
            %input.btn.btn-sm.btn-default{:type => 'submit', :value => t('views.common.filter')}

:javascript
  $(document).ready(function(){
    new RangePicker($('#score-control'), $('#score-from'), $('#score-to'));
  });

app/views/reports/_list.html.haml
.table-responsive
  %table.table.table-condensed.table-striped.table-vcentered
    %thead
      %tr
        - if params[:controller] == "reports"
          %th= sortable(:shop, t('activerecord.attributes.report.shop'))
          %th= sortable(:user, t('activerecord.attributes.report.user'))
          %th= sortable(:created_at, t('activerecord.attributes.report.created_at'))
          %th= sortable(:score, t('activerecord.attributes.report.score'))
          %th
        -else
          - unless params[:controller] == "shops"
            %th= t('activerecord.attributes.report.shop')
          - unless params[:controller] == "users"
            %th= t('activerecord.attributes.report.user')
          %th= t('activerecord.attributes.report.created_at')
          %th= t('activerecord.attributes.report.score')
          %th

    %tbody
      - if reports.any?
        - reports.each do |report|
          %tr
            - unless params[:controller] == "shops"
              %td= can_link_to(report.shop.name, report.shop)
            - unless params[:controller] == "users"
              %td= can_link_to(report.user.full_name, report.user)
            %td= report.created_at.strftime("%d.%m.%Y %H:%M")
            %td= report.score
            %td.text-right
              - if policy(report).show?
                %a.btn.btn-xs.btn-default{:href => report_path(report), :title => t('views.common.show'), :data => {:toggle => "tooltip"}}
                  %span.glyphicon.glyphicon-list

      - else
        %tr
          %td{:colspan => 5}
            %h4.text-center= t('views.common.empty')

app/views/reports/index.html.haml
%h2.text-center= t('views.reports.list')
%br

= render 'filter'

.row
  .col-lg-offset-1.col-lg-10
    .panel.panel-default
      = render 'list', :reports => @reports

    = paginate @reports

app/views/reports/show.html.haml
= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDMOPJqNEeELfg-Lt9yjIyCez3INjSvKq8&v=3'
= javascript_include_tag 'maps/report_show'
= stylesheet_link_tag 'shops'

.row
  .col-lg-offset-1.col-lg-10
    .well.well-sm
      .row
        .col-sm-6
          .panel.panel-default
            = render 'shop_photos/slideshow', :shop => @report.shop

        .col-sm-6
          %h3.text-center= t('views.reports.shop_info')
          .panel.panel-default
            = render 'shops/info', :shop => @report.shop

.row
  .col-lg-offset-1.col-lg-10
    .row
      .col-sm-6
        %h3= "#{t('views.reports.report_score')}: #{@report.score}"
        %hr

        %address
          = "#{t('activerecord.models.reviewer')}: "
          %br
          = "#{t('activerecord.attributes.user.name')}: "
          %strong= @report.user.full_name
          %br
          = "#{t('activerecord.attributes.user.email')}: "
          = @report.user.email
          %br
          = mail_to @report.user.email, t('views.common.send_mail'), :subject => "Report for '#{@report.shop.name}' completed at #{@report.created_at.strftime("%d %b %Y %H:%M")}", :body => "Report: #{report_url(@report)}"
        %hr

        %address
          = "#{t('activerecord.attributes.report.created_at')}: "
          = @report.created_at.strftime("%d %b %Y %H:%M")
          %br
          = link_to t('views.common.save_as_pdf'), report_path(@report, :format => :pdf)

      .col-sm-6
        .panel.panel-default
          #map_canvas.map-container{:data => {:markers => [{:url => asset_url('shop11.png'),
          :lat => @report.shop.latitude, :lng => @report.shop.longitude, :tooltip => t('activerecord.models.shop')},
          {:url => asset_url('blank15.png'), :lat => @report.latitude, :lng => @report.longitude,
          :tooltip => t('activerecord.models.report')}].to_json}}

%hr

.row
  .col-lg-offset-1.col-lg-10
    - @report.structured.each do |category, elements|
      .panel.panel-default
        .panel-heading
          %h4= category.name

        .list-group
          - elements.each do |e|
            .list-group-item
              .row
                .col-xs-6
                  = e.name
                .col-xs-6.text-right
                  = e.value

    = render 'report_photos/galery', :photos => @report.photos

app/views/reports/show.pdf.haml
= stylesheet_link_tag "shops"

.well.well-sm
  .row
    .col-xs-6
      %h3= "#{t('views.reports.report_score')}: #{@report.score}"
      %hr

      %address
        = "#{t('activerecord.models.reviewer')}: "
        %br
        = "#{t('activerecord.attributes.user.name')}: "
        %strong= @report.user.full_name
        %br
        = "#{t('activerecord.attributes.user.email')}: "
        = @report.user.email
      %hr

      %address
        = "#{t('activerecord.attributes.report.created_at')}: "
        = @report.created_at.strftime("%d %b %Y %H:%M")

    .col-xs-6
      %h3.text-center= t('views.reports.shop_info')
      %hr
      .panel.panel-default
        %table#general-info.table.table-condensed.table-striped
          %tbody
            %tr
              %td= t('activerecord.attributes.shop.region')
              %td= link_to @report.shop.region.name, @report.shop.region
            %tr
              %td= t('activerecord.attributes.shop.city')
              %td= link_to @report.shop.city.name, @report.shop.city
            %tr
              %td= t('activerecord.attributes.shop.address')
              %td= link_to @report.shop.address, @report.shop
            %tr
              %td= t('activerecord.attributes.shop.type')
              %td= @report.shop.type.name
            %tr
              %td= t('activerecord.attributes.shop.square_footage')
              %td= @report.shop.square_footage || '-'
            %tr
              %td= t('activerecord.attributes.shop.dealer')
              %td= link_to @report.shop.dealer.name, @report.shop.dealer
            %tr
              %td= t('activerecord.attributes.shop.user')
              %td= @report.shop.user ? link_to(@report.shop.user.full_name, @report.shop.user) : '-'

.row
  .col-lg-offset-1.col-lg-10
    - @report.structured.each do |category, elements|
      .panel.panel-default
        .panel-heading
          %h4= category.name

        .list-group
          - elements.each do |e|
            .list-group-item
              .row
                .col-xs-6
                  = e.name
                .col-xs-6.text-right
                  = e.value

    = render 'report_photos/galery', :photos => @report.photos