config/routes.rb
Rails.application.routes.draw do

  namespace 'api' do
    get '/mobile_app', :to => 'mobile_app#index', :as => 'mobile_app'

    post '/reports', :to => 'reports#create', :as => 'reports'
    get '/reports/structure', :to => 'reports#structure', :as => 'reports_structure'
    post '/reports/:id/photo', :to => 'reports#photo', :as => 'reports_photo'

    get '/shops', :to => 'shops#index', :as => 'shops'

    get '/settings/versions', :to => 'settings#versions', :as => 'settings_versions'

    post '/users/sign_in', :to => 'users#sign_in', :as => 'sign_in'
    post '/users/geolocation', :to => 'users#geolocation', :as => 'user_geolocation'
  end

  scope '(:locale)' do
    get '/charts/reports_score', :to => 'charts#reports_score', :as => 'reports_score_chart'
    get '/charts/reports_count', :to => 'charts#reports_count', :as => 'reports_count_chart'

    resources :cities do
      member do
        get 'restore'
        patch 'restore_info'
      end
    end

    resources :dealers do
      member do
        get 'restore'
      end
    end

    resources :employees do
      member do
        get 'restore'
      end
    end

    resources :employee_workpositions do
      member do
        get 'restore'
      end
    end

    resources :items

    resources :regions do
      member do
        get 'restore'
      end
    end

    resources :reports, :only => [:index, :show]

    resources :report_structure_categories do
      member do
        get 'increase_priority'
        get 'decrease_priority'
      end
    end

    resources :report_structure_elements do
      member do
        get 'increase_priority'
        get 'decrease_priority'
      end
    end

    get '/report_structure', :to => 'report_structure_categories#index', :as => 'report_structure'

    resources :settings, :only => [:index, :edit, :update]

    resources :shops do
      collection do
        get 'map_info'
      end

      member do
        get 'info'
        get 'restore'
        patch 'restore_info'
      end

      resources :employees do
        member do
          get 'restore'
        end
      end

      resources :shop_items, :only => [:index, :new, :create, :destroy]
    end

    resources :shop_items

    resources :shop_photos

    resources :shop_types do
      member do
        get 'restore'
      end
    end

    devise_for :users, controllers: { sessions: "users/sessions" }
    resources :users do
      member do
        get 'restore'
      end
    end

    resources :user_locations, :only => [:index] do
      collection do
        get 'map'
      end
    end

    resources :user_devices, :only => [:index, :destroy]
  end

  root 'dashboard#index'
  get '/:locale' => 'dashboard#index'
  match '/settings/review_associated_shops' => 'settings#review_associated_shops', via: [:get, :post]

end

app/models/report_structure_category.rb
class ReportStructureCategory < ActiveRecord::Base
  include Modules::SoftDelete
  
  validates :name,  :presence => true

  has_many :elements, :class_name => 'ReportStructureElement', :foreign_key => :report_structure_category_id, :dependent => :delete_all

  after_save -> { self.touch }
  after_soft_delete :delete_elements, :recalculate_priority
  after_create :set_priority
  after_touch :change_shop_structure_version

  def increase_priority
    return false if self.priority == 1

    new_priority = self.priority - 1
    category_to_change = ReportStructureCategory.find_by_priority(new_priority)
    category_to_change.update_attribute(:priority, category_to_change.priority + 1)
    self.update_attribute(:priority, new_priority)
    
    true
  end

  def decrease_priority
    return false if self.priority == ReportStructureCategory.count

    new_priority = self.priority + 1
    category_to_change = ReportStructureCategory.find_by_priority(new_priority)
    category_to_change.update_attribute(:priority, category_to_change.priority -  1)
    self.update_attribute(:priority, new_priority)

    true
  end

  private

  def set_priority
    count = ReportStructureCategory.count
    self.update_attribute(:priority, count)
  end

  def self.recalculate_priority
    ReportStructureCategory.order(:priority).each_with_index do |cat, index|
      cat.update_attribute(:priority, index + 1)
    end
  end

  def delete_elements
    elements.delete_all
    self.touch
  end

  def change_shop_structure_version
    Setting.change_version('report_structure_version')
  end

end

app/controllers/report_structure_categories_controller.rb
class ReportStructureCategoriesController < ApplicationController
  before_action :load_category, only: [:show, :edit, :update, :destroy, 
    :increase_priority, :decrease_priority]

  # GET /report_structure_categories
  def index
    @categories = ReportStructureCategory.order(:priority)
    authorize @categories
  end

  # GET /report_structure_categories/1
  def show
    if request.xhr?
      respond_to do |format|
        format.html { render :partial => 'header', :locals => {:category => @category} }
      end
    end
  end

  # GET /report_structure_categories/new
  def new
    @category = ReportStructureCategory.new

    if request.xhr?
      respond_to do |format|
        format.html { render :partial => 'new' }
      end
    end
  end

  # GET /report_structure_categories/1/edit
  def edit
    if request.xhr?
      respond_to do |format|
        format.html { render :partial => 'form' }
      end
    end
  end

  # POST /report_structure_categories
  def create
    @category = ReportStructureCategory.new(category_params)

    if request.xhr?
      if @category.save
        redirect_to @category
      else
        render :partial => 'form'
      end
    end
  end

  # PATCH/PUT /report_structure_categories/1
  def update
    if request.xhr?
      if @category.update(category_params)
        redirect_to @category
      else
        render :partial => 'form'
      end
    end
  end

  # DELETE /report_structure_categories/1
  def destroy
    @category.soft_delete

    render :nothing => true
  end

  # GET /report_structure_categories/1/increase_priority
  def increase_priority
    render :json => { :success => @category.increase_priority }
  end

  # GET /report_structure_categories/1/decrease_priority
  def decrease_priority
    render :json => { :success => @category.decrease_priority }
  end

  private

  def load_category
    @category = ReportStructureCategory.find(params[:id])
  end

  def category_params
    params.require(:report_structure_category).permit(:name,:priority)
  end
end

app/views/report_structure_categories/_form.html.haml
= simple_form_for(@category, :html => {:role => 'form'}, :wrapper => 'vertical_form') do |f|
  .row
    = f.input :name, :wrapper_html => {:class => 'col-sm-9'}, :label_html => {:class => 'sr-only'}, :input_html => {:class => 'input-sm'}

    .col-sm-3
      .btn-toolbar.text-right
        %a.btn.btn-sm.btn-default{:href => "javascript:;", :data => {:savecategory => true}}
          %span.glyphicon.glyphicon-ok

        %a.btn.btn-sm.btn-default{:href => @category.id ? report_structure_category_path(@category) : '', :data => {:showcategory => true}}
          %span.glyphicon.glyphicon-minus

app/views/report_structure_categories/_header.html.haml
.row
  .col-sm-9
    %h4= category.name
  .col-sm-3.text-right
    %a.btn.btn-sm.btn-default{:data => {:up => true, :parent => '.category-container.panel.panel-default', :action => increase_priority_report_structure_category_path(category, :format => :json)}}
      %span.glyphicon.glyphicon-arrow-up
    %a.btn.btn-sm.btn-default{:data => {:down => true, :parent => '.category-container.panel.panel-default', :action => decrease_priority_report_structure_category_path(category, :format => :json)}}
      %span.glyphicon.glyphicon-arrow-down
    %a.btn.btn-sm.btn-default{:href => "#{new_report_structure_element_path}?report_structure_element[report_structure_category_id]=#{category.id}", :data => {:newelement => true}}
      %span.glyphicon.glyphicon-plus

    %a.btn.btn-sm.btn-default{:href => edit_report_structure_category_path(category), :data => {:editcategory => true}}
      %span.glyphicon.glyphicon-edit

    %a.btn.btn-sm.btn-default{:href => report_structure_category_path(category), :data => {:deletecategory => true, :confirmation => t('views.common.confirm')}}
      %span.glyphicon.glyphicon-remove

app/views/report_structure_categories/_new.html.haml
.category-container.panel.panel-default
  .category-header.panel-heading
    =render :partial => 'form'

  .div-table.div-table-striped.div-table-condensed
    .div-thead
      .div-tr
        .div-th= t('activerecord.attributes.report_structure_element.name')
        .div-th= t('activerecord.attributes.report_structure_element.type')
        .div-th= t('activerecord.attributes.report_structure_element.weight')
        .div-th= t('activerecord.attributes.report_structure_element.shop_types')
        .div-th
    .element-list.div-tbody

app/views/report_structure_categories/_show.html.haml
.category-container.panel.panel-default
  .category-header.panel-heading
    = render 'report_structure_categories/header', :category => category

  .table-responsive
    .div-table.div-table-striped.div-table-condensed
      .div-thead
        .div-tr
          .div-th= t('activerecord.attributes.report_structure_element.name')
          .div-th= t('activerecord.attributes.report_structure_element.type')
          .div-th= t('activerecord.attributes.report_structure_element.weight')
          .div-th= t('activerecord.attributes.report_structure_element.shop_types')
          .div-th
      .element-list.div-tbody
        - category.elements.order(:priority).each do |elem|
          = render 'report_structure_elements/show', :element => elem


  

app/views/report_structure_categories/index.html.haml
= stylesheet_link_tag 'report_structure'

= javascript_include_tag 'report_structure'

.row
  .col-lg-offset-1.col-lg-7.col-sm-9
    %h2= t('views.report_structure.index')

  .col-sm-3
    %br
    .btn-toolbar.text-right
      %a.btn.btn.btn-primary{:href => new_report_structure_category_path, :data => {:newcategory => true}}= t('views.report_structure.add_category')

.row
  .col-lg-offset-1.col-lg-10.col-sm-9
    %input#review-associated-shops{:type => :checkbox, :data => {:setting => Setting::REVIEW_ASSOCIATED_SHOPS}}
    %label= t('views.report_structure.review_associated_shops')

%br

.row
  #report-structure.col-lg-offset-1.col-lg-10

    - @categories.each do |cat|
      = render 'report_structure_categories/show', :category => cat